// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: api/gobackup.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"` // "kvm01" or "production_group"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupRequest) Reset() {
	*x = BackupRequest{}
	mi := &file_api_gobackup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRequest) ProtoMessage() {}

func (x *BackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gobackup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRequest.ProtoReflect.Descriptor instead.
func (*BackupRequest) Descriptor() ([]byte, []int) {
	return file_api_gobackup_proto_rawDescGZIP(), []int{0}
}

func (x *BackupRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type BackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	JobId         string                 `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupResponse) Reset() {
	*x = BackupResponse{}
	mi := &file_api_gobackup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupResponse) ProtoMessage() {}

func (x *BackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gobackup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupResponse.ProtoReflect.Descriptor instead.
func (*BackupResponse) Descriptor() ([]byte, []int) {
	return file_api_gobackup_proto_rawDescGZIP(), []int{1}
}

func (x *BackupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BackupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BackupResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type WatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: Watch a specific job, or leave empty to watch all current activity
	JobId         string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_api_gobackup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gobackup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_api_gobackup_proto_rawDescGZIP(), []int{2}
}

func (x *WatchRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type LogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	IsSummary     bool                   `protobuf:"varint,2,opt,name=is_summary,json=isSummary,proto3" json:"is_summary,omitempty"` // if true, this goes to the top summary window instead of the raw scrolling log
	HostName      string                 `protobuf:"bytes,3,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	IsStatus      bool                   `protobuf:"varint,4,opt,name=is_status,json=isStatus,proto3" json:"is_status,omitempty"`
	Spinning      bool                   `protobuf:"varint,5,opt,name=spinning,proto3" json:"spinning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_api_gobackup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_gobackup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_api_gobackup_proto_rawDescGZIP(), []int{3}
}

func (x *LogChunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *LogChunk) GetIsSummary() bool {
	if x != nil {
		return x.IsSummary
	}
	return false
}

func (x *LogChunk) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *LogChunk) GetIsStatus() bool {
	if x != nil {
		return x.IsStatus
	}
	return false
}

func (x *LogChunk) GetSpinning() bool {
	if x != nil {
		return x.Spinning
	}
	return false
}

type GenerateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"` // e.g., "admin" or "viewer"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTokenRequest) Reset() {
	*x = GenerateTokenRequest{}
	mi := &file_api_gobackup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTokenRequest) ProtoMessage() {}

func (x *GenerateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gobackup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTokenRequest.ProtoReflect.Descriptor instead.
func (*GenerateTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_gobackup_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateTokenRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GenerateTokenRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type GenerateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTokenResponse) Reset() {
	*x = GenerateTokenResponse{}
	mi := &file_api_gobackup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTokenResponse) ProtoMessage() {}

func (x *GenerateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gobackup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTokenResponse.ProtoReflect.Descriptor instead.
func (*GenerateTokenResponse) Descriptor() ([]byte, []int) {
	return file_api_gobackup_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AddHostRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Group          string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Address        string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Port           int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	UseSudo        bool                   `protobuf:"varint,5,opt,name=use_sudo,json=useSudo,proto3" json:"use_sudo,omitempty"`
	RetentionCount int32                  `protobuf:"varint,6,opt,name=retention_count,json=retentionCount,proto3" json:"retention_count,omitempty"`
	Paths          []string               `protobuf:"bytes,7,rep,name=paths,proto3" json:"paths,omitempty"`
	Schedule       string                 `protobuf:"bytes,8,opt,name=schedule,proto3" json:"schedule,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddHostRequest) Reset() {
	*x = AddHostRequest{}
	mi := &file_api_gobackup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHostRequest) ProtoMessage() {}

func (x *AddHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gobackup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHostRequest.ProtoReflect.Descriptor instead.
func (*AddHostRequest) Descriptor() ([]byte, []int) {
	return file_api_gobackup_proto_rawDescGZIP(), []int{6}
}

func (x *AddHostRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddHostRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *AddHostRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddHostRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *AddHostRequest) GetUseSudo() bool {
	if x != nil {
		return x.UseSudo
	}
	return false
}

func (x *AddHostRequest) GetRetentionCount() int32 {
	if x != nil {
		return x.RetentionCount
	}
	return 0
}

func (x *AddHostRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *AddHostRequest) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

type AddHostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddHostResponse) Reset() {
	*x = AddHostResponse{}
	mi := &file_api_gobackup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHostResponse) ProtoMessage() {}

func (x *AddHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gobackup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHostResponse.ProtoReflect.Descriptor instead.
func (*AddHostResponse) Descriptor() ([]byte, []int) {
	return file_api_gobackup_proto_rawDescGZIP(), []int{7}
}

func (x *AddHostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddHostResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_api_gobackup_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gobackup_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_api_gobackup_proto_rawDescGZIP(), []int{8}
}

type HostInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address        string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Schedule       string                 `protobuf:"bytes,3,opt,name=schedule,proto3" json:"schedule,omitempty"`
	RetentionCount int32                  `protobuf:"varint,4,opt,name=retention_count,json=retentionCount,proto3" json:"retention_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	mi := &file_api_gobackup_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_gobackup_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_api_gobackup_proto_rawDescGZIP(), []int{9}
}

func (x *HostInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HostInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *HostInfo) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *HostInfo) GetRetentionCount() int32 {
	if x != nil {
		return x.RetentionCount
	}
	return 0
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []*HostInfo            `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_api_gobackup_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gobackup_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_api_gobackup_proto_rawDescGZIP(), []int{10}
}

func (x *ListResponse) GetHosts() []*HostInfo {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type PruneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PruneRequest) Reset() {
	*x = PruneRequest{}
	mi := &file_api_gobackup_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PruneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PruneRequest) ProtoMessage() {}

func (x *PruneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gobackup_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PruneRequest.ProtoReflect.Descriptor instead.
func (*PruneRequest) Descriptor() ([]byte, []int) {
	return file_api_gobackup_proto_rawDescGZIP(), []int{11}
}

type PruneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PruneResponse) Reset() {
	*x = PruneResponse{}
	mi := &file_api_gobackup_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PruneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PruneResponse) ProtoMessage() {}

func (x *PruneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gobackup_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PruneResponse.ProtoReflect.Descriptor instead.
func (*PruneResponse) Descriptor() ([]byte, []int) {
	return file_api_gobackup_proto_rawDescGZIP(), []int{12}
}

func (x *PruneResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PruneResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListBackupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupsRequest) Reset() {
	*x = ListBackupsRequest{}
	mi := &file_api_gobackup_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupsRequest) ProtoMessage() {}

func (x *ListBackupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gobackup_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupsRequest.ProtoReflect.Descriptor instead.
func (*ListBackupsRequest) Descriptor() ([]byte, []int) {
	return file_api_gobackup_proto_rawDescGZIP(), []int{13}
}

func (x *ListBackupsRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type BackupArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Modified      string                 `protobuf:"bytes,4,opt,name=modified,proto3" json:"modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupArchive) Reset() {
	*x = BackupArchive{}
	mi := &file_api_gobackup_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupArchive) ProtoMessage() {}

func (x *BackupArchive) ProtoReflect() protoreflect.Message {
	mi := &file_api_gobackup_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupArchive.ProtoReflect.Descriptor instead.
func (*BackupArchive) Descriptor() ([]byte, []int) {
	return file_api_gobackup_proto_rawDescGZIP(), []int{14}
}

func (x *BackupArchive) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *BackupArchive) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *BackupArchive) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BackupArchive) GetModified() string {
	if x != nil {
		return x.Modified
	}
	return ""
}

type ListBackupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Archives      []*BackupArchive       `protobuf:"bytes,1,rep,name=archives,proto3" json:"archives,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupsResponse) Reset() {
	*x = ListBackupsResponse{}
	mi := &file_api_gobackup_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupsResponse) ProtoMessage() {}

func (x *ListBackupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gobackup_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupsResponse.ProtoReflect.Descriptor instead.
func (*ListBackupsResponse) Descriptor() ([]byte, []int) {
	return file_api_gobackup_proto_rawDescGZIP(), []int{15}
}

func (x *ListBackupsResponse) GetArchives() []*BackupArchive {
	if x != nil {
		return x.Archives
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_gobackup_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gobackup_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_gobackup_proto_rawDescGZIP(), []int{16}
}

type UpcomingJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Schedule      string                 `protobuf:"bytes,2,opt,name=schedule,proto3" json:"schedule,omitempty"`
	NextRun       string                 `protobuf:"bytes,3,opt,name=next_run,json=nextRun,proto3" json:"next_run,omitempty"`
	NextUnix      int64                  `protobuf:"varint,4,opt,name=next_unix,json=nextUnix,proto3" json:"next_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpcomingJob) Reset() {
	*x = UpcomingJob{}
	mi := &file_api_gobackup_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpcomingJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpcomingJob) ProtoMessage() {}

func (x *UpcomingJob) ProtoReflect() protoreflect.Message {
	mi := &file_api_gobackup_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpcomingJob.ProtoReflect.Descriptor instead.
func (*UpcomingJob) Descriptor() ([]byte, []int) {
	return file_api_gobackup_proto_rawDescGZIP(), []int{17}
}

func (x *UpcomingJob) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *UpcomingJob) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *UpcomingJob) GetNextRun() string {
	if x != nil {
		return x.NextRun
	}
	return ""
}

func (x *UpcomingJob) GetNextUnix() int64 {
	if x != nil {
		return x.NextUnix
	}
	return 0
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Online        bool                   `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	ActiveJob     string                 `protobuf:"bytes,2,opt,name=active_job,json=activeJob,proto3" json:"active_job,omitempty"`
	QueuedJobs    []string               `protobuf:"bytes,3,rep,name=queued_jobs,json=queuedJobs,proto3" json:"queued_jobs,omitempty"`
	UpcomingJobs  []*UpcomingJob         `protobuf:"bytes,4,rep,name=upcoming_jobs,json=upcomingJobs,proto3" json:"upcoming_jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_gobackup_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gobackup_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_gobackup_proto_rawDescGZIP(), []int{18}
}

func (x *StatusResponse) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *StatusResponse) GetActiveJob() string {
	if x != nil {
		return x.ActiveJob
	}
	return ""
}

func (x *StatusResponse) GetQueuedJobs() []string {
	if x != nil {
		return x.QueuedJobs
	}
	return nil
}

func (x *StatusResponse) GetUpcomingJobs() []*UpcomingJob {
	if x != nil {
		return x.UpcomingJobs
	}
	return nil
}

var File_api_gobackup_proto protoreflect.FileDescriptor

const file_api_gobackup_proto_rawDesc = "" +
	"\n" +
	"\x12api/gobackup.proto\x12\bgobackup\"'\n" +
	"\rBackupRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\"[\n" +
	"\x0eBackupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\tR\x05jobId\"%\n" +
	"\fWatchRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x93\x01\n" +
	"\bLogChunk\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"is_summary\x18\x02 \x01(\bR\tisSummary\x12\x1b\n" +
	"\thost_name\x18\x03 \x01(\tR\bhostName\x12\x1b\n" +
	"\tis_status\x18\x04 \x01(\bR\bisStatus\x12\x1a\n" +
	"\bspinning\x18\x05 \x01(\bR\bspinning\"F\n" +
	"\x14GenerateTokenRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"-\n" +
	"\x15GenerateTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xde\x01\n" +
	"\x0eAddHostRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x19\n" +
	"\buse_sudo\x18\x05 \x01(\bR\auseSudo\x12'\n" +
	"\x0fretention_count\x18\x06 \x01(\x05R\x0eretentionCount\x12\x14\n" +
	"\x05paths\x18\a \x03(\tR\x05paths\x12\x1a\n" +
	"\bschedule\x18\b \x01(\tR\bschedule\"E\n" +
	"\x0fAddHostResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\r\n" +
	"\vListRequest\"}\n" +
	"\bHostInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1a\n" +
	"\bschedule\x18\x03 \x01(\tR\bschedule\x12'\n" +
	"\x0fretention_count\x18\x04 \x01(\x05R\x0eretentionCount\"8\n" +
	"\fListResponse\x12(\n" +
	"\x05hosts\x18\x01 \x03(\v2\x12.gobackup.HostInfoR\x05hosts\"\x0e\n" +
	"\fPruneRequest\"C\n" +
	"\rPruneResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x12ListBackupsRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\"o\n" +
	"\rBackupArchive\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x1a\n" +
	"\bmodified\x18\x04 \x01(\tR\bmodified\"J\n" +
	"\x13ListBackupsResponse\x123\n" +
	"\barchives\x18\x01 \x03(\v2\x17.gobackup.BackupArchiveR\barchives\"\x0f\n" +
	"\rStatusRequest\"u\n" +
	"\vUpcomingJob\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x1a\n" +
	"\bschedule\x18\x02 \x01(\tR\bschedule\x12\x19\n" +
	"\bnext_run\x18\x03 \x01(\tR\anextRun\x12\x1b\n" +
	"\tnext_unix\x18\x04 \x01(\x03R\bnextUnix\"\xa4\x01\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06online\x18\x01 \x01(\bR\x06online\x12\x1d\n" +
	"\n" +
	"active_job\x18\x02 \x01(\tR\tactiveJob\x12\x1f\n" +
	"\vqueued_jobs\x18\x03 \x03(\tR\n" +
	"queuedJobs\x12:\n" +
	"\rupcoming_jobs\x18\x04 \x03(\v2\x15.gobackup.UpcomingJobR\fupcomingJobs2\x95\x03\n" +
	"\rBackupService\x12@\n" +
	"\vStartBackup\x12\x17.gobackup.BackupRequest\x1a\x18.gobackup.BackupResponse\x129\n" +
	"\tWatchLogs\x12\x16.gobackup.WatchRequest\x1a\x12.gobackup.LogChunk0\x01\x12:\n" +
	"\tListHosts\x12\x15.gobackup.ListRequest\x1a\x16.gobackup.ListResponse\x12J\n" +
	"\vListBackups\x12\x1c.gobackup.ListBackupsRequest\x1a\x1d.gobackup.ListBackupsResponse\x12>\n" +
	"\tGetStatus\x12\x17.gobackup.StatusRequest\x1a\x18.gobackup.StatusResponse\x12?\n" +
	"\fPruneBackups\x12\x16.gobackup.PruneRequest\x1a\x17.gobackup.PruneResponse2\xa0\x01\n" +
	"\fAdminService\x12P\n" +
	"\rGenerateToken\x12\x1e.gobackup.GenerateTokenRequest\x1a\x1f.gobackup.GenerateTokenResponse\x12>\n" +
	"\aAddHost\x12\x18.gobackup.AddHostRequest\x1a\x19.gobackup.AddHostResponseB\x1bZ\x19gobackup/internal/grpc/pbb\x06proto3"

var (
	file_api_gobackup_proto_rawDescOnce sync.Once
	file_api_gobackup_proto_rawDescData []byte
)

func file_api_gobackup_proto_rawDescGZIP() []byte {
	file_api_gobackup_proto_rawDescOnce.Do(func() {
		file_api_gobackup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gobackup_proto_rawDesc), len(file_api_gobackup_proto_rawDesc)))
	})
	return file_api_gobackup_proto_rawDescData
}

var file_api_gobackup_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_gobackup_proto_goTypes = []any{
	(*BackupRequest)(nil),         // 0: gobackup.BackupRequest
	(*BackupResponse)(nil),        // 1: gobackup.BackupResponse
	(*WatchRequest)(nil),          // 2: gobackup.WatchRequest
	(*LogChunk)(nil),              // 3: gobackup.LogChunk
	(*GenerateTokenRequest)(nil),  // 4: gobackup.GenerateTokenRequest
	(*GenerateTokenResponse)(nil), // 5: gobackup.GenerateTokenResponse
	(*AddHostRequest)(nil),        // 6: gobackup.AddHostRequest
	(*AddHostResponse)(nil),       // 7: gobackup.AddHostResponse
	(*ListRequest)(nil),           // 8: gobackup.ListRequest
	(*HostInfo)(nil),              // 9: gobackup.HostInfo
	(*ListResponse)(nil),          // 10: gobackup.ListResponse
	(*PruneRequest)(nil),          // 11: gobackup.PruneRequest
	(*PruneResponse)(nil),         // 12: gobackup.PruneResponse
	(*ListBackupsRequest)(nil),    // 13: gobackup.ListBackupsRequest
	(*BackupArchive)(nil),         // 14: gobackup.BackupArchive
	(*ListBackupsResponse)(nil),   // 15: gobackup.ListBackupsResponse
	(*StatusRequest)(nil),         // 16: gobackup.StatusRequest
	(*UpcomingJob)(nil),           // 17: gobackup.UpcomingJob
	(*StatusResponse)(nil),        // 18: gobackup.StatusResponse
}
var file_api_gobackup_proto_depIdxs = []int32{
	9,  // 0: gobackup.ListResponse.hosts:type_name -> gobackup.HostInfo
	14, // 1: gobackup.ListBackupsResponse.archives:type_name -> gobackup.BackupArchive
	17, // 2: gobackup.StatusResponse.upcoming_jobs:type_name -> gobackup.UpcomingJob
	0,  // 3: gobackup.BackupService.StartBackup:input_type -> gobackup.BackupRequest
	2,  // 4: gobackup.BackupService.WatchLogs:input_type -> gobackup.WatchRequest
	8,  // 5: gobackup.BackupService.ListHosts:input_type -> gobackup.ListRequest
	13, // 6: gobackup.BackupService.ListBackups:input_type -> gobackup.ListBackupsRequest
	16, // 7: gobackup.BackupService.GetStatus:input_type -> gobackup.StatusRequest
	11, // 8: gobackup.BackupService.PruneBackups:input_type -> gobackup.PruneRequest
	4,  // 9: gobackup.AdminService.GenerateToken:input_type -> gobackup.GenerateTokenRequest
	6,  // 10: gobackup.AdminService.AddHost:input_type -> gobackup.AddHostRequest
	1,  // 11: gobackup.BackupService.StartBackup:output_type -> gobackup.BackupResponse
	3,  // 12: gobackup.BackupService.WatchLogs:output_type -> gobackup.LogChunk
	10, // 13: gobackup.BackupService.ListHosts:output_type -> gobackup.ListResponse
	15, // 14: gobackup.BackupService.ListBackups:output_type -> gobackup.ListBackupsResponse
	18, // 15: gobackup.BackupService.GetStatus:output_type -> gobackup.StatusResponse
	12, // 16: gobackup.BackupService.PruneBackups:output_type -> gobackup.PruneResponse
	5,  // 17: gobackup.AdminService.GenerateToken:output_type -> gobackup.GenerateTokenResponse
	7,  // 18: gobackup.AdminService.AddHost:output_type -> gobackup.AddHostResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_gobackup_proto_init() }
func file_api_gobackup_proto_init() {
	if File_api_gobackup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gobackup_proto_rawDesc), len(file_api_gobackup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_gobackup_proto_goTypes,
		DependencyIndexes: file_api_gobackup_proto_depIdxs,
		MessageInfos:      file_api_gobackup_proto_msgTypes,
	}.Build()
	File_api_gobackup_proto = out.File
	file_api_gobackup_proto_goTypes = nil
	file_api_gobackup_proto_depIdxs = nil
}
