// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: api/gobackup.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"` // "kvm01" or "production_group"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupRequest) Reset() {
	*x = BackupRequest{}
	mi := &file_api_gobackup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRequest) ProtoMessage() {}

func (x *BackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gobackup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRequest.ProtoReflect.Descriptor instead.
func (*BackupRequest) Descriptor() ([]byte, []int) {
	return file_api_gobackup_proto_rawDescGZIP(), []int{0}
}

func (x *BackupRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type BackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	JobId         string                 `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupResponse) Reset() {
	*x = BackupResponse{}
	mi := &file_api_gobackup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupResponse) ProtoMessage() {}

func (x *BackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gobackup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupResponse.ProtoReflect.Descriptor instead.
func (*BackupResponse) Descriptor() ([]byte, []int) {
	return file_api_gobackup_proto_rawDescGZIP(), []int{1}
}

func (x *BackupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BackupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BackupResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type WatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: Watch a specific job, or leave empty to watch all current activity
	JobId         string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_api_gobackup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gobackup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_api_gobackup_proto_rawDescGZIP(), []int{2}
}

func (x *WatchRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type LogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	IsSummary     bool                   `protobuf:"varint,2,opt,name=is_summary,json=isSummary,proto3" json:"is_summary,omitempty"` // if true, this goes to the top summary window instead of the raw scrolling log
	HostName      string                 `protobuf:"bytes,3,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_api_gobackup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_gobackup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_api_gobackup_proto_rawDescGZIP(), []int{3}
}

func (x *LogChunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *LogChunk) GetIsSummary() bool {
	if x != nil {
		return x.IsSummary
	}
	return false
}

func (x *LogChunk) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_gobackup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gobackup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_gobackup_proto_rawDescGZIP(), []int{4}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveJobs    int32                  `protobuf:"varint,1,opt,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	Uptime        string                 `protobuf:"bytes,2,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_gobackup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gobackup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_gobackup_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetActiveJobs() int32 {
	if x != nil {
		return x.ActiveJobs
	}
	return 0
}

func (x *StatusResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

type GenerateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"` // e.g., "admin" or "viewer"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTokenRequest) Reset() {
	*x = GenerateTokenRequest{}
	mi := &file_api_gobackup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTokenRequest) ProtoMessage() {}

func (x *GenerateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gobackup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTokenRequest.ProtoReflect.Descriptor instead.
func (*GenerateTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_gobackup_proto_rawDescGZIP(), []int{6}
}

func (x *GenerateTokenRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GenerateTokenRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type GenerateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTokenResponse) Reset() {
	*x = GenerateTokenResponse{}
	mi := &file_api_gobackup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTokenResponse) ProtoMessage() {}

func (x *GenerateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gobackup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTokenResponse.ProtoReflect.Descriptor instead.
func (*GenerateTokenResponse) Descriptor() ([]byte, []int) {
	return file_api_gobackup_proto_rawDescGZIP(), []int{7}
}

func (x *GenerateTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_api_gobackup_proto protoreflect.FileDescriptor

const file_api_gobackup_proto_rawDesc = "" +
	"\n" +
	"\x12api/gobackup.proto\x12\bgobackup\"'\n" +
	"\rBackupRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\"[\n" +
	"\x0eBackupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\tR\x05jobId\"%\n" +
	"\fWatchRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"Z\n" +
	"\bLogChunk\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"is_summary\x18\x02 \x01(\bR\tisSummary\x12\x1b\n" +
	"\thost_name\x18\x03 \x01(\tR\bhostName\"\x0f\n" +
	"\rStatusRequest\"I\n" +
	"\x0eStatusResponse\x12\x1f\n" +
	"\vactive_jobs\x18\x01 \x01(\x05R\n" +
	"activeJobs\x12\x16\n" +
	"\x06uptime\x18\x02 \x01(\tR\x06uptime\"F\n" +
	"\x14GenerateTokenRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"-\n" +
	"\x15GenerateTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\xcc\x01\n" +
	"\rBackupService\x12@\n" +
	"\vStartBackup\x12\x17.gobackup.BackupRequest\x1a\x18.gobackup.BackupResponse\x129\n" +
	"\tWatchLogs\x12\x16.gobackup.WatchRequest\x1a\x12.gobackup.LogChunk0\x01\x12>\n" +
	"\tGetStatus\x12\x17.gobackup.StatusRequest\x1a\x18.gobackup.StatusResponse2`\n" +
	"\fAdminService\x12P\n" +
	"\rGenerateToken\x12\x1e.gobackup.GenerateTokenRequest\x1a\x1f.gobackup.GenerateTokenResponseB\x1bZ\x19gobackup/internal/grpc/pbb\x06proto3"

var (
	file_api_gobackup_proto_rawDescOnce sync.Once
	file_api_gobackup_proto_rawDescData []byte
)

func file_api_gobackup_proto_rawDescGZIP() []byte {
	file_api_gobackup_proto_rawDescOnce.Do(func() {
		file_api_gobackup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gobackup_proto_rawDesc), len(file_api_gobackup_proto_rawDesc)))
	})
	return file_api_gobackup_proto_rawDescData
}

var file_api_gobackup_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_gobackup_proto_goTypes = []any{
	(*BackupRequest)(nil),         // 0: gobackup.BackupRequest
	(*BackupResponse)(nil),        // 1: gobackup.BackupResponse
	(*WatchRequest)(nil),          // 2: gobackup.WatchRequest
	(*LogChunk)(nil),              // 3: gobackup.LogChunk
	(*StatusRequest)(nil),         // 4: gobackup.StatusRequest
	(*StatusResponse)(nil),        // 5: gobackup.StatusResponse
	(*GenerateTokenRequest)(nil),  // 6: gobackup.GenerateTokenRequest
	(*GenerateTokenResponse)(nil), // 7: gobackup.GenerateTokenResponse
}
var file_api_gobackup_proto_depIdxs = []int32{
	0, // 0: gobackup.BackupService.StartBackup:input_type -> gobackup.BackupRequest
	2, // 1: gobackup.BackupService.WatchLogs:input_type -> gobackup.WatchRequest
	4, // 2: gobackup.BackupService.GetStatus:input_type -> gobackup.StatusRequest
	6, // 3: gobackup.AdminService.GenerateToken:input_type -> gobackup.GenerateTokenRequest
	1, // 4: gobackup.BackupService.StartBackup:output_type -> gobackup.BackupResponse
	3, // 5: gobackup.BackupService.WatchLogs:output_type -> gobackup.LogChunk
	5, // 6: gobackup.BackupService.GetStatus:output_type -> gobackup.StatusResponse
	7, // 7: gobackup.AdminService.GenerateToken:output_type -> gobackup.GenerateTokenResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_gobackup_proto_init() }
func file_api_gobackup_proto_init() {
	if File_api_gobackup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gobackup_proto_rawDesc), len(file_api_gobackup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_gobackup_proto_goTypes,
		DependencyIndexes: file_api_gobackup_proto_depIdxs,
		MessageInfos:      file_api_gobackup_proto_msgTypes,
	}.Build()
	File_api_gobackup_proto = out.File
	file_api_gobackup_proto_goTypes = nil
	file_api_gobackup_proto_depIdxs = nil
}
